name: ratatouille23
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  video_player: ^2.4.5
  page_transition: "^2.0.9"
  flutter_svg: ^2.0.1
  flutter_feather_icons: ^2.0.0+1
  intl: ^0.17.0
  http: ^0.13.4
  flutter_secure_storage: ^8.0.0
  provider: ^6.0.5
  get: ^4.6.5
  fl_chart: ^0.62.0
  time_machine: ^0.9.17
  firebase_core: ^2.24.2
  firebase_analytics: ^10.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.12.0"

  flutter_lints: ^2.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo_mouse_whiteyellow.png"


flutter:

  uses-material-design: true

  assets:
    - assets/video/
    - assets/images/
    - assets/fonts/
    - assets/icons/


  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
